CREATE TABLE [dbo].[CranLanguage]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Iso] CHAR(2) NOT NULL,
	[Name] VARCHAR(500) NOT NULL,
	[InsertUser]  VARCHAR (1000) NOT NULL DEFAULT SYSTEM_USER,
    [InsertDate]  DATETIME2 (7)  NOT NULL DEFAULT GETDATE(),
    [UpdateUser]  VARCHAR (1000) NOT NULL DEFAULT SYSTEM_USER,
    [UpdateDate]  DATETIME2 (7)  NOT NULL DEFAULT GETDATE()
)
