CREATE TABLE [dbo].[CranLogEntry] (
    [Id]      INT           IDENTITY (1, 1) NOT NULL,
    [Message] VARCHAR (MAX) NOT NULL,
    [Created] DATETIME2 (7) NOT NULL,
	[InsertUser]  VARCHAR (1000) NOT NULL DEFAULT SYSTEM_USER,
    [InsertDate]  DATETIME2 (7)  NOT NULL DEFAULT GETDATE(),
    [UpdateUser]  VARCHAR (1000) NOT NULL DEFAULT SYSTEM_USER,
    [UpdateDate]  DATETIME2 (7)  NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

